# Generated by Django 4.2.7 on 2023-11-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_staff_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedvideo',
            name='due_date',
            field=models.DateField(default='2023-11-07'),
            preserve_default=False,
        ),
    ]
