# Generated by Django 4.2.7 on 2023-11-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rentedvideo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='movie_year',
            field=models.IntegerField(default='2023'),
            preserve_default=False,
        ),
    ]
